name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish Roarshin.CommonTools
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        PROJECT_FILE_PATH: Roarshin.CommonTools/Roarshin.CommonTools.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish Roarshin.CommonTools.DependencyInjection
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        PROJECT_FILE_PATH: Roarshin.CommonTools.DependencyInjection/Roarshin.CommonTools.DependencyInjection.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
